C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\Dia2Lib.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\Microsoft.Diagnostics.Tracing.EventSource.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\Microsoft.DiagnosticsHub.Packaging.InteropEx.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\AMD64\msdia140.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\x86\DiagnosticsHub.Packaging.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\x86\DiagnosticsHub.Packaging.Interop.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\x86\msdia140.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\x86\tdh.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfViewExtensions\msvcdis110.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfViewExtensions\msvcp110.dll
C:\Users\Vancem\Source\Repos\perfview\src\PerfViewExtensions\msvcr110.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\Interop.Dia2Lib.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\OSExtensions.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\amd64\KernelTraceControl.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\amd64\msdia140.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\arm\KernelTraceControl.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\relogger\TraceReloggerLib.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\x86\KernelTraceControl.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\x86\KernelTraceControl.Win61.dll
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\x86\msdia140.dll
C:\Users\Vancem\Source\Repos\perfview\src\robocopy.exe
C:\Users\Vancem\Source\Repos\perfview\src\updatePerfView.exe
C:\Users\Vancem\Source\Repos\perfview\src\EtwClrProfiler\MC.Exe
C:\Users\Vancem\Source\Repos\perfview\src\OSExtensions\SyncEncrypted.exe
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\Tutorial.exe
C:\Users\Vancem\Source\Repos\perfview\src\PerfView\SupportDlls\x86\sd.exe
C:\Users\Vancem\Source\Repos\perfview\src\PerfViewExtensions\PdbScope.exe
C:\Users\Vancem\Source\Repos\perfview\src\tools\CorFlags.exe
C:\Users\Vancem\Source\Repos\perfview\src\TraceEvent\traceparsergen.exe
