#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")
#pragma autorecover

[Dynamic,
  Description("ASP.NET Events") : amended,
  Guid("{AFF081FE-0247-4275-9C4E-021F3DC1DA35}"),
  locale("MS\\0x409")]
class AspNetTrace : EventTrace
{
    [Description ("Enable Flags") : amended,
        ValueDescriptions{
            "Infrastructure Events",
            "Pipeline Module Events",
            "Page Events",
            "Application Services Events" } : amended,
        DefineValues{
            "ETW_ASPNET_INFRASTRUCTURE",
            "ETW_ASPNET_MODULE",    
            "ETW_ASPNET_PAGE",          
            "ETW_ASPNET_APPSVC" },
        Values{
            "Infrastructure",
            "Module",
            "Page",
            "AppServices" },
        ValueMap{
            "0x0001",
            "0x0002",
            "0x0004",
            "0x0008"}
    ]
    uint32 Flags;

    [Description ("Levels") : amended,
        ValueDescriptions{
            "Abnormal exit or termination",
            "Severe errors",
            "Warnings",
            "Information",
            "Detailed information" } : amended,
        DefineValues{
            "TRACE_LEVEL_FATAL",
            "TRACE_LEVEL_ERROR", 
            "TRACE_LEVEL_WARNING",
            "TRACE_LEVEL_INFORMATION",           
            "TRACE_LEVEL_VERBOSE" },                   
        Values{
            "Fatal",
            "Error",
            "Warning",
            "Information",
            "Verbose" },
        ValueMap{
            "0x1",
            "0x2",
            "0x3",
            "0x4",
            "0x5" },
        ValueType("index")
    ]
    uint32 Level;
};

[Dynamic,
 Description("ASP.NET Request") : amended,
 Guid("{06A01367-79D3-4594-8EB3-C721603C4679}"),
 DisplayName("AspNetReq"),
 locale("MS\\0x409")
]
class AspNetTraceEvent : AspNetTrace
{

};

[Dynamic,
 Description("Start") : amended,
 EventType(1),
 EventLevel(0),
 EventTypeName("Start") : amended
]
class AspNetStart : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended,
    read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId; 

    [WmiDataId(3),
    Description("Method") : amended,
    StringTermination("NullTerminated"),
    read]
    string  Method;

    [WmiDataId(4),
    Description("Path") : amended,
    StringTermination("NullTerminated"),
    read]
    string  Path;

    [WmiDataId(5),
    Description("QueryString") : amended,
    StringTermination("NullTerminated"),
    read]
    string  QueryString;
};

[Dynamic,
 Description("End") : amended,
 EventType(2),
 EventLevel(0),
 EventTypeName("End") : amended
]
class AspNetStop : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended,
    read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId; 
};

[Dynamic,
 Description("RequestQueued") : amended,
 EventType(3), 
 EventLevel(4),
 EventTypeName("RequestQueued") : amended
]
class AspNetRequestQueued : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId; 
};

[Dynamic, Description("RequestDequeued") : amended,
 EventType(4), 
 EventLevel(4),
 EventTypeName("RequestDequeued") : amended]
class AspNetRequestDequeued : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("GetAppDomainEnter") : amended,
 EventType(5), 
 EventLevel(5),
 EventTypeName("GetAppDomainEnter") : amended
]
class AspNetGetAppDomainEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("GetAppDomainLeave") : amended,
 EventType(6), 
 EventLevel(5),
 EventTypeName("GetAppDomainLeave") : amended
]
class AspNetGetAppDomainLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic,
 Description("AppDomainEnter") : amended,
 EventType(7), 
 EventLevel(5),
 EventTypeName("AppDomainEnter") : amended
]
class AspNetAppDomainEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("DomainId") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  DomainId;
};

[Dynamic, Description("StartHandler") : amended,
 EventType(8), 
 EventLevel(5),
 EventTypeName("StartHandler") : amended]
class AspNetStartHandler : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;


    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("HandlerName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  HandlerName;

    [WmiDataId(4),
    Description("EventName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  EventName;
};

[Dynamic, Description("EndHandler") : amended,
 EventType(9), 
 EventLevel(5),
 EventTypeName("EndHandler") : amended]
class AspNetEndHandler : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PipelineModuleEnter") : amended,
 EventType(10), 
 EventLevel(5),
 EventTypeName("PipelineModuleEnter") : amended]
class AspNetPipelineModuleEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("ModuleName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  ModuleName;
};

[Dynamic, Description("PipelineModuleLeave") : amended,
 EventType(11), 
 EventLevel(5),
 EventTypeName("PipelineModuleLeave") : amended]
class AspNetPipelineModuleLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("ModuleName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  ModuleName;
};

[Dynamic, Description("MapHandlerEnter") : amended,
 EventType(12), 
 EventLevel(5),
 EventTypeName("MapHandlerEnter") : amended]
class AspNetMapHandlerEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("MapHandlerLeave") : amended,
 EventType(13), 
 EventLevel(5),
 EventTypeName("MapHandlerLeave") : amended]
class AspNetMapHandlerLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("ParseEnter") : amended,
 EventType(14), 
 EventLevel(5),
 EventTypeName("ParseEnter") : amended]
class AspNetParseEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("ParseLeave") : amended,
 EventType(15), 
 EventLevel(5),
 EventTypeName("ParseLeave") : amended]
class AspNetParseLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("CompileEnter") : amended,
 EventType(16), 
 EventLevel(5),
 EventTypeName("CompileEnter") : amended]
class AspNetCompileEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("CompileLeave") : amended,
 EventType(17), 
 EventLevel(5),
 EventTypeName("CompileLeave") : amended]
class AspNetCompileLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("Files") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Files;

    [WmiDataId(4),
    Description("Status") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Status;
};

[Dynamic, Description("HttpHandlerEnter") : amended,
 EventType(18), 
 EventLevel(4),
 EventTypeName("HttpHandlerEnter") : amended]
class AspNetHttpHandlerEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("HttpHandlerLeave") : amended,
 EventType(19), 
 EventLevel(4),
 EventTypeName("HttpHandlerLeave") : amended]
class AspNetHttpHandlerLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("SessionStatePartitionStart") : amended,
 EventType(20), 
 EventLevel(5),
 EventTypeName("SessionStatePartitionStart") : amended]
class AspNetSessionStatePartitionStart : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("ResolverType") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  ResolverType;

    [WmiDataId(4),
    Description("SessionId") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  SessionId;
};

[Dynamic, Description("SessionStatePartitionEnd") : amended,
 EventType(21), 
 EventLevel(5),
 EventTypeName("SessionStatePartitionEnd") : amended]
class AspNetSessionStatePartitionEnd : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("ResolverResult") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  ResolverResult;
};

[Dynamic, Description("PagePreInitEnter") : amended,
 EventType(22), 
 EventLevel(5),
 EventTypeName("PagePreInitEnter") : amended]
class AspNetPagePreInitEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PagePreInitLeave") : amended,
 EventType(23), 
 EventLevel(5),
 EventTypeName("PagePreInitLeave") : amended]
class AspNetPagePreInitLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageInitEnter") : amended,
 EventType(24), 
 EventLevel(5),
 EventTypeName("PageInitEnter") : amended]
class AspNetPageInitEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageInitLeave") : amended,
 EventType(25), 
 EventLevel(5),
 EventTypeName("PageInitLeave") : amended]
class AspNetPageInitLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadViewstateEnter") : amended,
 EventType(26), 
 EventLevel(5),
 EventTypeName("PageLoadViewstateEnter") : amended]
class AspNetPageLoadViewstateEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadViewstateLeave") : amended,
 EventType(27), 
 EventLevel(5),
 EventTypeName("PageLoadViewstateLeave") : amended]
class AspNetPageLoadViewstateLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadPostDataEnter") : amended,
 EventType(28), 
 EventLevel(5),
 EventTypeName("PageLoadPostDataEnter") : amended]
class AspNetPageLoadPostDataEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadPostDataLeave") : amended,
 EventType(29), 
 EventLevel(5),
 EventTypeName("PageLoadPostDataLeave") : amended]
class AspNetPageLoadPostDataLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadEnter") : amended,
 EventType(30), 
 EventLevel(5),
 EventTypeName("PageLoadEnter") : amended]
class AspNetPageLoadEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageLoadLeave") : amended,
 EventType(31), 
 EventLevel(5),
 EventTypeName("PageLoadLeave") : amended]
class AspNetPageLoadLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PagePostDataChangedEnter") : amended,
 EventType(32), 
 EventLevel(5),
 EventTypeName("PagePostDataChangedEnter") : amended]
class AspNetPagePostDataChangedEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PagePostDataChangedLeave") : amended,
 EventType(33), 
 EventLevel(5),
 EventTypeName("PagePostDataChangedLeave") : amended]
class AspNetPagePostDataChangedLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageRaisePostbackEnter") : amended,
 EventType(34), 
 EventLevel(5),
 EventTypeName("PageRaisePostbackEnter") : amended]
class AspNetPageRaisePostbackEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageRaisePostbackLeave") : amended,
 EventType(35), 
 EventLevel(5),
 EventTypeName("PageRaisePostbackLeave") : amended]
class AspNetPageRaisePostbackLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PagePreRenderEnter") : amended,
 EventType(36), 
 EventLevel(5),
 EventTypeName("PagePreRenderEnter") : amended]
class AspNetPagePreRenderEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PagePreRenderLeave") : amended,
 EventType(37), 
 EventLevel(5),
 EventTypeName("PagePreRenderLeave") : amended]
class AspNetPagePreRenderLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageSaveViewstateEnter") : amended,
 EventType(38), 
 EventLevel(5),
 EventTypeName("PageSaveViewstateEnter") : amended]
class AspNetPageSaveViewstateEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageSaveViewstateLeave") : amended,
 EventType(39), 
 EventLevel(5),
 EventTypeName("PageSaveViewstateLeave") : amended]
class AspNetPageSaveViewstateLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageRenderEnter") : amended,
 EventType(40), 
 EventLevel(5),
 EventTypeName("PageRenderEnter") : amended]
class AspNetPageRenderEnter : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("PageRenderLeave") : amended,
 EventType(41), 
 EventLevel(5),
 EventTypeName("PageRenderLeave") : amended]
class AspNetPageRenderLeave : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("SessionDataBegin") : amended,
 EventType(42), 
 EventLevel(4),
 EventTypeName("SessionDataBegin") : amended]
class AspNetAcquireSessionBegin : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("SessionDataEnd") : amended,
 EventType(43), 
 EventLevel(4),
 EventTypeName("SessionDataEnd") : amended]
class AspNetAcquireSessionEnd : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("ProfileBegin") : amended,
 EventType(44), 
 EventLevel(4),
 EventTypeName("ProfileBegin") : amended]
class AspNetProfileBegin : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("ProfileEnd") : amended,
 EventType(45), 
 EventLevel(4),
 EventTypeName("ProfileEnd") : amended]
class AspNetProfileEnd : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("User") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  User;
};

[Dynamic, Description("RoleManagerIsUserInRole") : amended,
 EventType(46), 
 EventLevel(4),
 EventTypeName("RoleManagerIsUserInRole") : amended]
class AspNetRoleManagerIsUserInRole : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("Provider") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Provider;

    [WmiDataId(4),
    Description("User") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  User;

    [WmiDataId(5),
    Description("Role") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Role;

    [WmiDataId(6),
    Description("Status") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Status;
};

[Dynamic, Description("RoleManagerGetUserRoles") : amended,
 EventType(47), 
 EventLevel(4),
 EventTypeName("RoleManagerGetUserRoles") : amended]
class AspNetRoleManagerGetUserRoles : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("Provider") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Provider;

    [WmiDataId(4),
    Description("User") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  User;

    [WmiDataId(5),
    Description("Roles") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Roles;
};

[Dynamic, Description("RoleManagerBegin") : amended,
 EventType(48), 
 EventLevel(4),
 EventTypeName("RoleManagerBegin") : amended]
class AspNetRoleManagerBegin : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("RoleManagerEnd") : amended,
 EventType(49), 
 EventLevel(4),
 EventTypeName("RoleManagerEnd") : amended]
class AspNetRoleManagerEnd: AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("Provider") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  Provider;

    [WmiDataId(4),
    Description("User") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  User;
};

[Dynamic, Description("WebEventRaiseStart") : amended,
 EventType(50), 
 EventLevel(5),
 EventTypeName("WebEventRaiseStart") : amended]
class AspNetWebEventRaiseStart: AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("EventClassName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  EventClassName;

    [WmiDataId(4),
    Description("EventCode") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  EventCode;

    [WmiDataId(5),
    Description("EventDetailCode") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  EventDetailCode;
};

[Dynamic, Description("WebEventRaiseEnd") : amended,
 EventType(51), 
 EventLevel(5),
 EventTypeName("WebEventRaiseEnd") : amended]
class AspNetWebEventRaiseEnd: AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("WebEventDeliverStart") : amended,
 EventType(52), 
 EventLevel(5),
 EventTypeName("WebEventDeliverStart") : amended]
class AspNetWebEventDeliverStart: AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(3),
    Description("ProviderName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  ProviderName;

    [WmiDataId(4),
    Description("RuleName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  RuleName;

    [WmiDataId(5),
    Description("EventGroupName") : amended,
    StringTermination("NullTerminated"),
    format("w"),
    read]
    string  EventGroupName;
};

[Dynamic, Description("WebEventDeliverEnd") : amended,
 EventType(53), 
 EventLevel(5),
 EventTypeName("WebEventDeliverEnd") : amended]
class AspNetWebEventDeliverEnd: AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended, read]
    uint64 ConnID;

    [WmiDataId(2),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;
};

[Dynamic, Description("TraceContext Warning Trace") : amended,
 EventType(59), 
 EventLevel(3),
 EventVersion(0),
 EventTypeName("TraceContextWarning") : amended]
class AspNetPageTraceWarnEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWarningMsg;
};

[Dynamic, Description("TraceContext Write Trace") : amended,
 EventType(60), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("TraceContextWrite") : amended]
class AspNetPageTraceWriteEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Critical") : amended,
 EventType(61), 
 EventLevel(1),
 EventVersion(0),
 EventTypeName("DiagnosticTraceCritical") : amended]
class AspNetModuleDiagCriticalEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Error") : amended,
 EventType(62), 
 EventLevel(3),
 EventVersion(0),
 EventTypeName("DiagnosticTraceError") : amended]
class AspNetModuleDiagErrorEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Warning") : amended,
 EventType(63), 
 EventLevel(3),
 EventVersion(0),
 EventTypeName("DiagnosticTraceWarning") : amended]
class AspNetModuleDiagWarningEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Info") : amended,
 EventType(64), 
 EventLevel(4),
 EventVersion(0),
 EventTypeName("DiagnosticTraceInfo") : amended]
class AspNetModuleDiagInfoEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Verbose") : amended,
 EventType(65), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceVerbose") : amended]
class AspNetModuleDiagVerboseEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Start") : amended,
 EventType(66), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceStart") : amended]
class AspNetModuleDiagStartEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Stop") : amended,
 EventType(67), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceStop") : amended]
class AspNetModuleDiagStopEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Suspend") : amended,
 EventType(68), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceSuspend") : amended]
class AspNetModuleDiagSuspendEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Resume") : amended,
 EventType(69), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceResume") : amended]
class AspNetModuleDiagResumeEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};

[Dynamic, Description("Diagnostic Trace Transfer") : amended,
 EventType(70), 
 EventLevel(5),
 EventVersion(0),
 EventTypeName("DiagnosticTraceTransfer") : amended]
class AspNetModuleDiagTransferEvent : AspNetTraceEvent
{

    [WmiDataId(1),
     Description("Context ID") : amended,
     extension("Guid"),
     ActivityID,
     read]
     object  ContextId;

    [WmiDataId(2),
    Description("uri") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  Uri;

    [WmiDataId(3),
    Description("eventData") : amended,
    StringTermination("NullTerminated"),
    format("w"),    
    read]
    string  TraceWriteMsg;
};
